name: GitHub Actions Demo
on: [push]


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: update file to webserver 
        uses: forechoandlook/forechoandlook.github.io@main
        with:
            user: ubuntu
            args: "-avz --delete"
            host: 3.19.62.107
            port: 22
            key: ${{ secrets.MAC }}
            local_path: './docs/*'
            # target_path: "/var/www/omicsml.ai/html/"
            target_path: /home/ubuntu/test/
