name: GitHub Actions Demo
on: [push]


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: update file to webserver 
        uses: actions/checkout@v3
        with:
            username: ubuntu
            server: 3.19.62.107
            port: 22
            ssh_private_key: ${{ secrets.MAC }}
            local_path: './docs/*'
            # target_path: "/var/www/omicsml.ai/html/"
            target_path: '/home/ubuntu/test/'

      - name: test
        run: echo 1234456