name: GitHub Actions Demo
on: [push]

env:
    SERVER_PRIVATE_KEY: ${{ secrets.mac }} # 服务器私钥
    SERVER_HOST: ${{ 3.19.62.107 }} # 服务器IP地址
    USER_NAME: ${{ ubuntu }} # 服务器用户名
    cache-name: note


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: update file to webserver 
        uses: actions/checkout@v3
        with:
            SSH_PRIVATE_KEY: ${{ env.SERVER_PRIVATE_KEY }}
            local_path: "./docs/*"
            # target_path: "/var/www/omicsml.ai/html/"
            target_path: "/home/ubuntu/test/"

